version: "3"

services:
  frontend:
    build: ./frontend
    networks:
      - app-network

  backend:
    build: ./backend
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gurustech_db
      POSTGRES_USER: gurustech_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8090:8090"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
      - adminer
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
