version: "3.7"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - VITE_API_URL=/api
    volumes:
      - frontend-build:/usr/share/nginx/html

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - frontend-build:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  frontend-build:
